package rs.ac.uns.ftn.admin.model;

import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2019.06.16 at 06:29:05 PM CEST 
//
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import com.fasterxml.jackson.annotation.JsonIgnore;


/**
* <p>Java class for anonymous complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType>
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}ID"/>
*         &lt;element name="ServiceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
*       &lt;/sequence>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
 "id",
 "serviceName"
})
@XmlRootElement(name = "FacilityAS")
@Entity
public class FacilityAS {

	 @XmlElement(name = "id", required = true)
	// @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	 @XmlID
	 @XmlSchemaType(name = "id")
	 @Id
	 @GeneratedValue(strategy=GenerationType.IDENTITY)
	 protected Long id;
	 
	 @XmlElement(name = "ServiceName", required = true)
	 @Column(name="serviceName",nullable=false)
	 protected String name;
	 
	 
	
	 public Long getId() {
		return id;
	}



	public void setId(Long id) {
		this.id = id;
	}



	/**
	  * Sets the value of the id property.
	  * 
	  * @param value
	  *     allowed object is
	  *     {@link String }
	  *     
	  */
//	 public void setID(String value) {
//	     this.id = value;
//	 }
	
	 /**
	  * Gets the value of the serviceName property.
	  * 
	  * @return
	  *     possible object is
	  *     {@link String }
	  *     
	  */
	 public String getName() {
	     return name;
	 }
	
	 /**
	  * Sets the value of the serviceName property.
	  * 
	  * @param value
	  *     allowed object is
	  *     {@link String }
	  *     
	  */
	 public void setName(String value) {
	     this.name = value;
	 }

}
