server:
  port: ${PORT:8761}

spring:
  application:
    name: discovery

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false