//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.05 at 06:45:40 PM CEST 
//


package megatravel.data.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accommodationFacility" type="{http://megatravel/data/xsd}AccommodationFacility" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="accommodationUnit" type="{http://megatravel/data/xsd}AccommodationUnit" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="reservation" type="{http://megatravel/data/xsd}Reservation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="pricePerMonth" type="{http://megatravel/data/xsd}PricePerMonth" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="category" type="{http://megatravel/data/xsd}Category" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="unitAS" type="{http://megatravel/data/xsd}UnitAS" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="facilityAS" type="{http://megatravel/data/xsd}FacilityAS" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="facilityType" type="{http://megatravel/data/xsd}FacilityType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="location" type="{http://megatravel/data/xsd}Location" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="destination" type="{http://megatravel/data/xsd}Destination" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accommodationFacility",
    "accommodationUnit",
    "reservation",
    "pricePerMonth",
    "category",
    "unitAS",
    "facilityAS",
    "facilityType",
    "location",
    "destination"
})
@XmlRootElement(name = "GetSyncBaseResponse")
public class GetSyncBaseResponse {

    protected List<AccommodationFacility> accommodationFacility;
    protected List<AccommodationUnit> accommodationUnit;
    protected List<Reservation> reservation;
    protected List<PricePerMonth> pricePerMonth;
    protected List<Category> category;
    protected List<UnitAS> unitAS;
    protected List<FacilityAS> facilityAS;
    protected List<FacilityType> facilityType;
    protected List<Location> location;
    protected List<Destination> destination;

    /**
     * Gets the value of the accommodationFacility property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accommodationFacility property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccommodationFacility().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccommodationFacility }
     * 
     * 
     */
    public List<AccommodationFacility> getAccommodationFacility() {
        if (accommodationFacility == null) {
            accommodationFacility = new ArrayList<AccommodationFacility>();
        }
        return this.accommodationFacility;
    }

    /**
     * Gets the value of the accommodationUnit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accommodationUnit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccommodationUnit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccommodationUnit }
     * 
     * 
     */
    public List<AccommodationUnit> getAccommodationUnit() {
        if (accommodationUnit == null) {
            accommodationUnit = new ArrayList<AccommodationUnit>();
        }
        return this.accommodationUnit;
    }

    /**
     * Gets the value of the reservation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reservation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReservation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Reservation }
     * 
     * 
     */
    public List<Reservation> getReservation() {
        if (reservation == null) {
            reservation = new ArrayList<Reservation>();
        }
        return this.reservation;
    }

    /**
     * Gets the value of the pricePerMonth property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pricePerMonth property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPricePerMonth().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PricePerMonth }
     * 
     * 
     */
    public List<PricePerMonth> getPricePerMonth() {
        if (pricePerMonth == null) {
            pricePerMonth = new ArrayList<PricePerMonth>();
        }
        return this.pricePerMonth;
    }

    /**
     * Gets the value of the category property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the category property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Category }
     * 
     * 
     */
    public List<Category> getCategory() {
        if (category == null) {
            category = new ArrayList<Category>();
        }
        return this.category;
    }

    /**
     * Gets the value of the unitAS property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the unitAS property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnitAS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UnitAS }
     * 
     * 
     */
    public List<UnitAS> getUnitAS() {
        if (unitAS == null) {
            unitAS = new ArrayList<UnitAS>();
        }
        return this.unitAS;
    }

    /**
     * Gets the value of the facilityAS property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the facilityAS property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFacilityAS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FacilityAS }
     * 
     * 
     */
    public List<FacilityAS> getFacilityAS() {
        if (facilityAS == null) {
            facilityAS = new ArrayList<FacilityAS>();
        }
        return this.facilityAS;
    }

    /**
     * Gets the value of the facilityType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the facilityType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFacilityType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FacilityType }
     * 
     * 
     */
    public List<FacilityType> getFacilityType() {
        if (facilityType == null) {
            facilityType = new ArrayList<FacilityType>();
        }
        return this.facilityType;
    }

    /**
     * Gets the value of the location property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the location property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Location }
     * 
     * 
     */
    public List<Location> getLocation() {
        if (location == null) {
            location = new ArrayList<Location>();
        }
        return this.location;
    }

    /**
     * Gets the value of the destination property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the destination property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDestination().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Destination }
     * 
     * 
     */
    public List<Destination> getDestination() {
        if (destination == null) {
            destination = new ArrayList<Destination>();
        }
        return this.destination;
    }

}
