//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.05 at 06:45:40 PM CEST 
//


package megatravel.data.xsd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the megatravel.data.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: megatravel.data.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetInboxMessagesResponse }
     * 
     */
    public GetInboxMessagesResponse createGetInboxMessagesResponse() {
        return new GetInboxMessagesResponse();
    }

    /**
     * Create an instance of {@link GetSyncBaseRequest }
     * 
     */
    public GetSyncBaseRequest createGetSyncBaseRequest() {
        return new GetSyncBaseRequest();
    }

    /**
     * Create an instance of {@link GetSyncBaseResponse }
     * 
     */
    public GetSyncBaseResponse createGetSyncBaseResponse() {
        return new GetSyncBaseResponse();
    }

    /**
     * Create an instance of {@link PostReservationRealizationRequest }
     * 
     */
    public PostReservationRealizationRequest createPostReservationRealizationRequest() {
        return new PostReservationRealizationRequest();
    }

    /**
     * Create an instance of {@link PostNewMessageResponse }
     * 
     */
    public PostNewMessageResponse createPostNewMessageResponse() {
        return new PostNewMessageResponse();
    }

    /**
     * Create an instance of {@link Reservation }
     * 
     */
    public Reservation createReservation() {
        return new Reservation();
    }

    /**
     * Create an instance of {@link PostNewAccommodationFacilityResponse }
     * 
     */
    public PostNewAccommodationFacilityResponse createPostNewAccommodationFacilityResponse() {
        return new PostNewAccommodationFacilityResponse();
    }

    /**
     * Create an instance of {@link AccommodationUnit }
     * 
     */
    public AccommodationUnit createAccommodationUnit() {
        return new AccommodationUnit();
    }

    /**
     * Create an instance of {@link UnitAS }
     * 
     */
    public UnitAS createUnitAS() {
        return new UnitAS();
    }

    /**
     * Create an instance of {@link PostNewMessageRequest }
     * 
     */
    public PostNewMessageRequest createPostNewMessageRequest() {
        return new PostNewMessageRequest();
    }

    /**
     * Create an instance of {@link PostReservationRealizationResponse }
     * 
     */
    public PostReservationRealizationResponse createPostReservationRealizationResponse() {
        return new PostReservationRealizationResponse();
    }

    /**
     * Create an instance of {@link PostNewReservationRequest }
     * 
     */
    public PostNewReservationRequest createPostNewReservationRequest() {
        return new PostNewReservationRequest();
    }

    /**
     * Create an instance of {@link GetAllReservationsResponse }
     * 
     */
    public GetAllReservationsResponse createGetAllReservationsResponse() {
        return new GetAllReservationsResponse();
    }

    /**
     * Create an instance of {@link GetAllUnitASRequest }
     * 
     */
    public GetAllUnitASRequest createGetAllUnitASRequest() {
        return new GetAllUnitASRequest();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link PostNewReservationResponse }
     * 
     */
    public PostNewReservationResponse createPostNewReservationResponse() {
        return new PostNewReservationResponse();
    }

    /**
     * Create an instance of {@link GetSentMessagesRequest }
     * 
     */
    public GetSentMessagesRequest createGetSentMessagesRequest() {
        return new GetSentMessagesRequest();
    }

    /**
     * Create an instance of {@link FacilityType }
     * 
     */
    public FacilityType createFacilityType() {
        return new FacilityType();
    }

    /**
     * Create an instance of {@link Rating }
     * 
     */
    public Rating createRating() {
        return new Rating();
    }

    /**
     * Create an instance of {@link GetInboxMessagesRequest }
     * 
     */
    public GetInboxMessagesRequest createGetInboxMessagesRequest() {
        return new GetInboxMessagesRequest();
    }

    /**
     * Create an instance of {@link PricePerMonth }
     * 
     */
    public PricePerMonth createPricePerMonth() {
        return new PricePerMonth();
    }

    /**
     * Create an instance of {@link GetSentMessagesResponse }
     * 
     */
    public GetSentMessagesResponse createGetSentMessagesResponse() {
        return new GetSentMessagesResponse();
    }

    /**
     * Create an instance of {@link GetAllUnitASResponse }
     * 
     */
    public GetAllUnitASResponse createGetAllUnitASResponse() {
        return new GetAllUnitASResponse();
    }

    /**
     * Create an instance of {@link AccommodationFacility }
     * 
     */
    public AccommodationFacility createAccommodationFacility() {
        return new AccommodationFacility();
    }

    /**
     * Create an instance of {@link Destination }
     * 
     */
    public Destination createDestination() {
        return new Destination();
    }

    /**
     * Create an instance of {@link FacilityAS }
     * 
     */
    public FacilityAS createFacilityAS() {
        return new FacilityAS();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link GetAllReservationsRequest }
     * 
     */
    public GetAllReservationsRequest createGetAllReservationsRequest() {
        return new GetAllReservationsRequest();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link PostNewAccommodationFacilityRequest }
     * 
     */
    public PostNewAccommodationFacilityRequest createPostNewAccommodationFacilityRequest() {
        return new PostNewAccommodationFacilityRequest();
    }

}
