//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.09 at 04:33:23 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://megatravel/data/xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package megatravel.data.xsd;
